version: '3.1'

services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor

  atutor:
    build: ./App
    restart: always
    ports:
      - 8080:80
