version: '3.1'

services:
  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor

  db:
    image: plopix/docker-mysqlproxyprofiler
    restart: always
    depends_on:
      - mysql
    environment:
      BACKEND: "mysql:3306"

  atutor:
    build: ./App
    restart: always
    ports:
      - 8080:80
